# Docker image for running tests
FROM golang:alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go mod tidy

# Install migrate CLI
RUN apk add --no-cache curl \
    && curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xz -C /usr/local/bin

# Database URL for testing
ENV DATABASE_URL=postgres://postgres:password@postgres:5432/postgres?sslmode=disable

# Set up the entry point
CMD ["sh", "-c", "migrate -path /app/internal/repository/postgres/migrations -database ${DATABASE_URL} up && go test ./..."]
