version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - test_data:/var/lib/postgresql/data

  booking_service:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  test_data:
